sudo: required
dist: bionic
language: node_js
node_js:
  - '12.6.0'
cache:
  directories:
    - 'node_modules'
addons:
  ssh_known_hosts: 18.195.102.38
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_fd781ff8b527_key -iv $encrypted_fd781ff8b527_iv -in spotishare.pem.enc -out spotishare.pem -d
  - eval "$(ssh-agent -s)"
  - chmod 600 spotishare.pem
  - ssh-add spotishare.pem
script:
  - bash deploy.sh